source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'CTNotificationServiceExample' do
  pod "CleverTap-iOS-SDK"
end

target 'NotificationService' do
  pod "CTNotificationService"
  pod "CleverTap-iOS-SDK"
end

